### ISSUE TITLE
关于 php bin/hyperf.php apidog:ui 执行的时候,直接提示 Uncaught ReflectionException: Method index does not exist报错

### ISSUE THREAD

**Issue by pixiaoxiao** [daodao97/apidog#62]
PHP Fatal error:  Uncaught ReflectionException: Method index does not exist in /home/vagrant/hyperf-test/vendor/hyperf/di/src/ReflectionManager.php:45
Stack trace:
#0 /home/vagrant/hyperf-test/vendor/hyperf/di/src/ReflectionManager.php(45): ReflectionClass->getMethod()
#1 /home/vagrant/hyperf-test/vendor/daodao97/apidog/src/ApiAnnotation.php(22): Hyperf\Di\ReflectionManager::reflectMethod()
#2 /home/vagrant/hyperf-test/vendor/daodao97/apidog/src/Swagger/SwaggerJson.php(76): Hyperf\Apidog\ApiAnnotation::methodMetadata()
#3 /home/vagrant/hyperf-test/vendor/daodao97/apidog/src/BootAppConfListener.php(63): Hyperf\Apidog\Swagger\SwaggerJson->addPath()
#4 [internal function]: Hyperf\Apidog\BootAppConfListener->Hyperf\Apidog\{closure}()
#5 /home/vagrant/hyperf-test/vendor/daodao97/apidog/src/BootAppConfListener.php(65): array_walk_recursive()
#6 /home/vagrant/hyperf-test/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\Apidog\BootAppConfListener->process()
#7 /home/vagrant/hyperf-test/vendor/hyperf/framework/src/ApplicationFac in /home/vagrant/hyperf-test/vendor/hyperf/di/src/ReflectionManager.php on line 45

**Comment by pixiaoxiao** [comment]
大佬,找到问题了, 通过注解定义路由声明的路由跟插件不能共存,只能通过标准的路由来声明
